### ISSUE TITLE
amdDependencies in default template has some problem

### ISSUE THREAD

**Issue by farthinker** [bebraw/libumd#13]
Consider this example:

```
if (typeof define === 'function' && define.amd) {
  // AMD. Register as an anonymous module unless amdModuleId is set
  define('simple-uploader', ["jquery","simple-module"], function (jquery, simple-module) {
    return (root['uploader'] = factory(jquery, simple-module));
  });
}
```

Above snippets is generated by the default umd.hbs. The corresponding part is:

```
if (typeof define === 'function' && define.amd) {
  // AMD. Register as an anonymous module unless amdModuleId is set
  define({{#if amdModuleId}}'{{amdModuleId}}', {{/if}}[{{{amdDependencies.wrapped}}}], function ({{{amdDependencies.normal}}}) {
    return ({{#if objectToExport}}root['{{{objectToExport}}}'] = {{/if}}factory({{{amdDependencies.normal}}}));
  });
}
```

As you can see, the amd module id is possiblely illegal as a js variable.

**Comment by bebraw** [comment]
Yeah, there isn't conversion for those parameters yet. What if I put them through [title-case](https://www.npmjs.com/package/title-case)? Can you see any potential issues with that or do you have a better idea?

**Comment by bebraw** [comment]
Actually the function we're looking for is [snake-case](https://www.npmjs.com/package/snake-case). Demo:

```bash
> s = require('snake-case')
> s('foo-bar')
'foo_bar'
> s('foo_bar')
'foo_bar'
```

You can see the potential problem above. `-` and `_` get the same treatment.

Of course we can go totally generic and generate alphabets for the parameters or something but that doesn't sound very readable.

**Comment by bebraw** [comment]
The most "JavaScripty" solution would be to use [camel-case](https://www.npmjs.com/package/camel-case) but there's the same mapping problem.

**Comment by farthinker** [comment]
Good work :) I'll take the alphabets params solution.
