### ISSUE TITLE
Influencing the factory function argument names

### ISSUE THREAD

**Issue by Download** [bebraw/libumd#14]
I'm using libumd (through [grunt-umd](https://github.com/bebraw/grunt-umd)) to create an UMD module that depends on another UMD module named `memorystorage`, that exports a default function called `MemoryStorage`. Libumd ends up naming the function parameter `memorystorage` (all lowercase) but I would like it to use `MemoryStorage` instead. 

Here is my config:

```javascript
umd: {
	all: {
		options: {
			src: '<%= pkg.main %>',
			dest: '<%= pkg.dist.umd %>', 
			objectToExport: '<%= pkg.exports[0] %>',
			amdModuleId: '<%= pkg.name %>',
			deps: {'default': ['memorystorage']}
		}
	}
},
```
The output looks like this:
```javascript
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define('webdb', ["memorystorage"], function (a0) {
      return (root['WebDB'] = factory(a0));
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("memorystorage"));
  } else {
    root['WebDB'] = factory(memorystorage);
  }
}(this, function (memorystorage) {

  // my code comes here

}));
```

The problem is on the last line before my code:

```javascript
}(this, function (memorystorage) {
```

I want this line to read:

```javascript
}(this, function (MemoryStorage) {
```

Is there a way for me to influence what the function argument names will be?

I also asked [this same question](https://github.com/bebraw/grunt-umd/issues/29) on the grunt-umd issue list. The author thinks it would require changes here. 

It seems like a common scenario... Any tricks to make this work?

**Comment by bebraw** [comment]
Yeah, I'm the author. :+1:

As stated in the thread there, I expect you'll need to extend libumd to support the suggested syntax. I'm more than happy to accept the object format you proposed at the original thread.

**Comment by Download** [comment]
I'm willing to have a look... Do you have any pointers to get me started? Is there a Contributor Guide or something?

Or maybe you could give me a 3 minute walkthrough of steps needed?

I'm thinking:

1. fork this repo
2. Make a branch `factoryArgumentNames`
3. Hack the code
4. Run grunt to `compile` my changes
5. Run tests
6. Submit a PR

something along those lines? Please correct me where I'm wrong.

**Comment by bebraw** [comment]
I don't have any particular guide for this project as it's so small. If you can, try following the existing coding conventions. Also note how I write my commit messages. This helps with consistency.

Your steps sound fine to me. I'm happy as long as we don't break backwards compatibility. Thanks for contributing. :+1:

**Comment by Download** [comment]
I see `libumd` is not using grunt... Am I correct I have to signup with Travis and push something to run the tests? I have never used Travis before...

**Comment by Download** [comment]
> Thanks for contributing.

Don't thank me just yet... I'll make you work for it!  :)

**Comment by bebraw** [comment]
Yeah, there's no Grunt setup here, that's correct.

Testing is a little problematic. Now it relies on [Saucelabs](https://saucelabs.com/). It runs against multiple browsers remotely there.

It is actually possible to operate on Saucelabs locally through `npm test`. This expects that you have set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` env variables locally. Of course the problem is that you'll need a Saucelabs account to get these...

If this sounds a little much, I can refactor the tests so that you can actually run something locally against a headless browser. I actually don't mind at all if you want to have a go at it. The current tests just trigger umdified code through a browser and then assert the right values were printed.

[Karma runner](https://karma-runner.github.io) would likely work very well for this purpose. [zuul](https://github.com/defunctzombie/zuul) would be another good alternative.

I suppose we'll have to fix the testing approach first before we can start to worry about the rest.

**Comment by Download** [comment]
I already found Saucelabs and created an account there (through the Travis page). I ran `npm test` and it was complaining about `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` just like you said... It's telling me to change `.travis.yml` which seems weird to me...

Don't worry about refactoring the tests... I'll work with what you have (it doesn't sound bad at all).

Is it expected for me to be changing `.travis.yml`?  Looking at this setup it seems it might actually be better to leave it out of Git as it seems to be a personal file?

I'm almost there. I just want to be able to run the tests so I can verify mu changes.

**Comment by bebraw** [comment]
Some bits have likely changed below... I set those sauce env vars and tried running the tests locally. It just doesn't complete. Same with Travis.

I'll try bumping deps etc. to see if there's an easy way around this. If not, then we need to test against a headless browser like PhantomJS.

**Comment by Download** [comment]
> I'm almost there.

Mmmm scrap that.  `gem install travis` fails, preventing me to run `travis encrypt SAUCE_USERNAME=Download_github --add` 
(as always when I try to use Ruby.. I don't think anything Ruby ever worked first-time for me, I hate Ruby!)

I tried to `set SAUCE_USERNAME=[THE LONG STRING FROM TRAVIS.YML]` but it complains that it's not the right format and something.

I'm giving up for the moment. I have hacked the UMD template and hardcoded my argument name in it, fixing my immediate problem. 

I'll retry once you made your changes. I'm not comfortable hacking the `libumd` code if I can't test my changes.

**Comment by bebraw** [comment]
Yeah, that's understandable. I'll try to get the tests fixed so we can move on with this. :+1:

**Comment by bebraw** [comment]
`set SAUCE_USERNAME=[THE LONG STRING FROM TRAVIS.YML]` won't work btw. `SAUCE_USERNAME` refers to your account name at Saucelabs if I remember right. Anyway, it doesn't work at the moment so no need to spend time on that...

**Comment by Download** [comment]
Ok i'll hold off for the moment  :+1:

**Comment by bebraw** [comment]
@Download I patched it to run the tests against local browsers. I know it's not ideal and I would rather do something headless (phantom) but it's a good step towards something better. It should be ok to work on the project now. :+1:

**Comment by bebraw** [comment]
@Download It runs the tests through Phantom now. I think this will work better for us.

**Comment by Download** [comment]
Ok.. I had issues with the tests against local browsers. They kept failing with complaints about locked files. Will try again with the new setup.

**Comment by Download** [comment]
I did `npm install -g phantomjs`, `npm install` and then `npm test`.
It does not really give me any output, but I suppose that's ok?

```sh
\Documents\GitHub\libumd>npm test

> libumd@0.6.1 test \Documents\GitHub\libumd
> node tests

Active code page: 65001

\Documents\GitHub\libumd>
```

**Comment by bebraw** [comment]
Yup. Exactly.

It should give an error if it fails to load the script.

Now that I think of it, it should capture Phantom output and assert it
prints but I'll do that today.

**Comment by bebraw** [comment]
@Download I improved the tests further. Now you should see three "ok"'s if everything went fine. Also got rid of requirejs while at it as it didn't work fine for some reason. It was too difficult to understand why so I threw something far simpler in place just for testing.

**Comment by Download** [comment]
I have been looking at the code but have a hard time figuring it out... 
All code is in index.js right?

Am I right in thinking that `convertDependencyArrays(deps)` would be a good place to start looking at?

**Comment by bebraw** [comment]
It's probably easier to work from template to code. In `umd.hbs` you can see a line like

```javascript
}(this, function ({{dependencies}}) {
```

Based on that we find

```javascript
UMD.prototype.generate = function generate() {
    ...

    ctx.dependencies = deps.join(', ');

    ...
};
```

That part would have to change somehow. The rest should cascade from this change.

And yes, `convertDependencyArrays` seems to require a change as well.

**Comment by Download** [comment]
Yes I kinda saw that as a given. But you are right, that's the way to approach it.

I created a branch `plan-of-attack` on my fork and added comments to index.js documenting my thoughts and assumptions... Could you maybe have a look at it and correct me where needed?

https://github.com/Download/libumd/commit/455b38b8bb453b27c2ffe4646f1d46a6b22fca06

**Comment by Download** [comment]
Mmm I'm looking at the code again but have maybe misunderstood some things.

I have the feeling that once I wrap my head around this the change itself isn't actually that difficult... But  I'm still having trouble understanding it all... I especially don't get how you can grab `deps` directly from  the defaults:

```javascript
var deps = defaultDeps ? defaultDeps || defaultDeps.items || [] : [];
```

and then (if I'm not missing something) assign them to ctx using the line you pasted... Without processing the user options somehow?

```javascript
// where are the user options incorporated into this?? deps.join would just join the default deps??
ctx.dependencies = deps.join(', ');
```

**Comment by bebraw** [comment]
We'll probably save some time if I do the work based on your spec. Can you provide me the interface you want? I recall the object format you proposed initially was sane. Even putting that to a test form will help a lot even if the test doesn't pass. :+1:

**Comment by Download** [comment]
That sounds like a great plan. I had a very busy day and will have one coming up tomorrow as well, so it may take some time, but writing up a nice test case sounds very doable. Your refactoring of the testing helped btw, I can now run the tests successfully. So once I get a bit more time I wil go for that.

**Comment by bebraw** [comment]
Cool. No hurry. :+1:

**Comment by Download** [comment]
Ok so I started by making some tests that actually need dependencies. I pushed my work so far to a new branch:
https://github.com/Download/libumd/tree/tests-for-dependencies

I added a data/with-deps.js file that depends on data/browser.js (which just creates and returns a function test()). data/with-deps.js creates and returns a function testDeps that calls test. The browser version of this is working, but I'm hitting a roadblock with the AMD version. It was failing saying that `undefined is not a function` on the line that calls `test()`...

I couldn't figure it out so I printed the code to the console instead of running it in PhantomJS and this is what I got:

```javascript
var modules = {};

window.define = function(name, deps, cb) {
  modules[name] = cb();
};
window.define.amd = true;

window.require = function(deps, module) {
  module.apply(null, getModules(deps));

  function getModules(names) {
    return names.map(function(name) {
      return modules[name];
    });
  }
};
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define('test', [], function () {
      return (factory());
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory();
  } else {
    root['test'] = factory();
  }
}(this, function () {

return function test() {
    console.log('executed');

    window.close();
};


}));
(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module unless amdModuleId is set
    define('testDeps', ["test"], function (a0) {
      return (factory(a0));
    });
  } else if (typeof exports === 'object') {
    // Node. Does not work with strict CommonJS, but
    // only CommonJS-like environments that support module.exports,
    // like Node.
    module.exports = factory(require("test"));
  } else {
    root['testDeps'] = factory(test);
  }
}(this, function (test) {

return function testDeps() {
    test();

    window.close();
};


}));

require(['testDeps'], function(testDeps) {/* testDeps(); */});
```

Look carefully at this bit of code:

```javascript
    // AMD. Register as an anonymous module unless amdModuleId is set
    define('testDeps', ["test"], function (a0) {
      return (factory(a0));
    });
```

It is doing exactly what I would expect: `define`ing a module that has `"test"` as a dependency... But now look at the implementation of `define`:

```javascript
window.define = function(name, deps, cb) {
  modules[name] = cb();
};
```

It is completely ignoring the dependencies passed to it!

I am not sure why you are writing the `define` and `require` functions yourself, but I think actually changing the definition of `define` so it is able to handle dependencies is non-trivial...

**Comment by bebraw** [comment]
> I am not sure why you are writing the define and require functions yourself, but I think actually changing the definition of define so it is able to handle dependencies is non-trivial...

Yeah, that's quite possible. I didn't get requirejs work with the setup so I did something really ghetto that I understand. I can do dependency resolution algorithm if needed but let's hope it doesn't need to get into that. :)

Of course if we can find some light solution that's AMD compatible, we can definitely go with that and save some effort. Maybe something like [almond](https://www.npmjs.com/package/almond) would work?

Those `window.close();` bits aren't likely needed as Phantom can kill the window just fine.

**Comment by Download** [comment]
I can ignore it for now and just rely on the browser version that is working...

I will write the test for dependecies with alias and just test the browser version.

**Comment by bebraw** [comment]
Cool, once you're done I'll merge your work and look into AMD and implementation of course.

**Comment by Download** [comment]
I'm hoping this will be helpful. Let me know if you need some changes to it.

**Comment by bebraw** [comment]
Thanks! I'll work based on this. :+1:

**Comment by bebraw** [comment]
@Download I gave it a go. Implementation at the repo. Feel free to try out. Let me know how that goes. If it's ok, I'll publish a new version and get that grunt wrapper updated.

**Comment by Download** [comment]
Ok thanks I'll try this out this week and let you know how it went.

**Comment by bebraw** [comment]
@Download Any luck? Tests pass and as far as I understand we should be good to go with a release. Best of all it's all backwards compatible.

**Comment by Download** [comment]
Ah sorry I had a very busy week and didn't get the time to test it. The fact that the project I needed this for now no longer needs it because it's no longer using the dependency doesn't help :)

Anyway I'll have a look right now.

**Comment by Download** [comment]
It looks great!  :+1: 

I feel a little ashamed now I made you wait ten days for this. It actually only took a few minutes to pull in the new code and run the tests. They all ran successful as you said. I had a look at the code and I think it does exactly what we want.

I haven't found the output files... I think it actuallu does it all in-memory right?

Anyway the `data/with-deps-and-alias.js` file clearly calls `alias()`, which can only work if you implemented the changes correctly, so I'd say we are good to go!

**Comment by bebraw** [comment]
No worries.

> I haven't found the output files... I think it actuallu does it all in-memory right?

Yeah. It does just a couple of extra operations if it detect an object.

> Anyway the data/with-deps-and-alias.js file clearly calls alias(), which can only work if you implemented the changes correctly, so I'd say we are good to go!

Yup. I'll push a new release.

**Comment by Download** [comment]
:+1:  Great work!

**Comment by bebraw** [comment]
I have to check how `default` works before releasing. Related: https://github.com/bebraw/grunt-umd/issues/30 .

Anyway, thanks for your contribution. I'll get a release out after checking that particular issue.
